/********************************************************************
* MyRepo_MyPackageDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyRepo_MyPackageDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyRepo_MyPackageDict();
extern void G__cpp_setup_inheritanceMyRepo_MyPackageDict();
extern void G__cpp_setup_typetableMyRepo_MyPackageDict();
extern void G__cpp_setup_memvarMyRepo_MyPackageDict();
extern void G__cpp_setup_globalMyRepo_MyPackageDict();
extern void G__cpp_setup_memfuncMyRepo_MyPackageDict();
extern void G__cpp_setup_funcMyRepo_MyPackageDict();
extern void G__set_cpp_environmentMyRepo_MyPackageDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "sample.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyRepo_MyPackageDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyRepo_MyPackageDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyRepo_MyPackageDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyRepo_MyPackageDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyRepo_MyPackageDictLN_sample;

/* STUB derived class for protected member access */
